### ISSUE TITLE
Сообщения об ошибке чтения из базы

### ISSUE THREAD

**Issue by fizruk** [cmc-haskell-2015/conway-life#1]
Всё, кажется, работает, но в консоли возникают ошибки:

```
$ cabal run
Preprocessing executable 'conway-life' for conway-life-0.1...
[3 of 4] Compiling Graphics         ( src/Graphics.hs, dist/build/conway-life/conway-life-tmp/Graphics.o )
Linking dist/build/conway-life/conway-life ...
Running conway-life...
Error reading database: file 'error1' wasn't loaded
Error reading database: file 'error2' wasn't loaded
Error reading database: file 'error3' wasn't loaded
```

**Comment by PodnimatelPingvinov** [comment]
Добрый день, базу данных делала Катя, но она мне рассказала в чем суть. Эти
файлы специально демонстрируют, что будет, если в директории с
конфигами/объектами лежат файлы с неправильным содержимым - они не будут
загружаться, о чем и пишется в консоли. Оставшиеся правильные файлы при
этом подгрузятся, поэтому все работает. Достаточно удалить файлы error1...3
и ошибок не будет.
18.05.2015 14:20 пользователь "Nickolay Kudasov" notifications@github.com
написал:

**Comment by fizruk** [comment]
Ясно, я думаю, можно убрать эти файлы из репозитория и написать об этом поведении в документации.

**Comment by fizruk** [comment]
Closed by eca246e.
